### ISSUE TITLE
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by Vananananana** [mikel-brostrom/Yolov5_StrongSORT_OSNet#412]
(base) F:\Github\Yolov5_DeepSort_OSNet>python track.py --source 0
F:\Github\Yolov5_DeepSort_OSNet\deep_sort/deep/reid\torchreid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(
Traceback (most recent call last):
  File "F:\Github\Yolov5_DeepSort_OSNet\track.py", line 308, in <module>
    main(opt)
  File "F:\Github\Yolov5_DeepSort_OSNet\track.py", line 303, in main
    run(**vars(opt))
  File "E:\Anaconda\install_here\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\Github\Yolov5_DeepSort_OSNet\track.py", line 93, in run
    (save_dir / 'tracks' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
  File "E:\Anaconda\install_here\lib\pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:\\Github\\Yolov5_DeepSort_OSNet\\weights\\yolov5m_F:\\Github\\Yolov5_DeepSort_OSNet\\weights\\osnet_x0_25_msmt17'

**Comment by LudvigKnast** [comment]
I have the same problem.

**Comment by haiduo** [comment]
这么明显错误，感觉就是作者故意bug

**Comment by Forzapovski** [comment]
I get the same error when I try to run track.py (after cloning the repository and downloading the requirements)

**Comment by mikel-brostrom** [comment]
Thanks @haiduo for pointing this out. `tracker.py` now updated
