### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by Sorawit-Khumnaewnak** [mikel-brostrom/Yolov5_StrongSORT_OSNet#427]
Hello.
I have error
![image](https://user-images.githubusercontent.com/48942280/173726099-6ece2970-2621-45b0-93ba-9aeacfbda2ec.png)
(StrongSORT) C:\Users\TUFFX505DU\Desktop\DEEP\Yolov5_StrongSORT_OSNet>python track.py --source 0
C:\Users\TUFFX505DU\Desktop\DEEP\Yolov5_StrongSORT_OSNet\strong_sort/deep/reid\torchreid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(
track: yolo_weights=C:\Users\TUFFX505DU\Desktop\DEEP\Yolov5_StrongSORT_OSNet\weights\yolov5m.pt, strong_sort_weights=C:\Users\TUFFX505DU\Desktop\DEEP\Yolov5_StrongSORT_OSNet\weights\osnet_x0_25_msmt17.pt, config_strongsort=strong_sort/configs/strong_sort.yaml, source=0, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_vid=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\track, name=None, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
Traceback (most recent call last):
  File "track.py", line 318, in <module>
    main(opt)
  File "track.py", line 313, in main
    run(**vars(opt))
  File "C:\Users\TUFFX505DU\Envs\StrongSORT\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 91, in run
    (save_dir / 'tracks' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
  File "C:\Users\TUFFX505DU\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\TUFFX505DU\\Desktop\\DEEP\\Yolov5_StrongSORT_OSNet\\weights\\yolov5m_C:\\Users\\TUFFX505DU\\Desktop\\DEEP\\Yolov5_StrongSORT_OSNet\\weights\\osnet_x0_25_msmt17'

**Comment by Sorawit-Khumnaewnak** [comment]
I fixed the issue by updating => "parser.add_argument('--name', default='exp', help='save results to project/name')"
![image](https://user-images.githubusercontent.com/48942280/173727234-a7d88729-b3c1-411b-8c18-51cb00ff22b3.png)
