### ISSUE TITLE
 No such file or directory: '/content/Yolov5_StrongSORT_OSNet/weights' when running on Google Colab

### ISSUE THREAD

**Issue by nqa112** [mikel-brostrom/Yolov5_StrongSORT_OSNet#438]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Tracking

### Bug

My code
`!python track.py --source [insert youtube link here] --yolo-weights ../runs/train/exp3/weights/best.pt --imgsz 640 --conf-thres 0.5 --iou-thres 0.5 --save-vid --line-thickness 2 --hide-conf`

I saved my yolov5 weights in Drive and upload it in runtime with the path `../runs/train/exp3/weights/best.pt`
My current working dir: `/content/Yolov5_StrongSORT_OSNet`

I cloned this repo exactly what the tutorial says, and I cannot find `weights` as this error says:
```
strong_sort/deep/reid/torchreid/metrics/rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '
track: yolo_weights=['/content/runs/train/exp3/weights/best.pt'], strong_sort_weights=/content/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.pt, config_strongsort=strong_sort/configs/strong_sort.yaml, source=https://www.youtube.com/watch?v=aIrEogSwOWQ, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_vid=True, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/track, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False
YOLOv5 🚀 2022-6-23 Python-3.7.13 torch-1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)

Fusing layers... 
YOLOv5m summary: 290 layers, 20865057 parameters, 0 gradients
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
cv2.imshow() is disabled in Google Colab environments
1/1: https://www.youtube.com/watch?v=aIrEogSwOWQ...  Success (1643 frames 1280x720 at 30.00 FPS)

Traceback (most recent call last):
  File "track.py", line 321, in <module>
    main(opt)
  File "track.py", line 316, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 128, in run
    ema_alpha=cfg.STRONGSORT.EMA_ALPHA,
  File "/content/Yolov5_StrongSORT_OSNet/strong_sort/strong_sort.py", line 32, in __init__
    gdown.download(model_url, str(model_weights), quiet=False)
  File "/usr/local/lib/python3.7/dist-packages/gdown/download.py", line 202, in download
    for file in os.listdir(osp.dirname(output) or "."):
FileNotFoundError: [Errno 2] No such file or directory: '/content/Yolov5_StrongSORT_OSNet/weights'
terminate called without an active exception
```

**Comment by yangzgtyut** [comment]
I have the same problem

**Comment by nqa112** [comment]
**My solution**: Don't know if this is a path bug, I found that those strongsort weights lie at:
`Yolov5_StrongSORT_OSNet/strong_sort/deep/checkpoint`

So I would add argument like this, for example:
```
--strong-sort-weights strong_sort/deep/checkpoint/osnet_x0_25_msmt17.pth
```
