### ISSUE TITLE
Sizes of tensors must match except in dimension 1. Expected size 46 but got size 45 for tensor number 1 in the list

### ISSUE THREAD

**Issue by yxtay2324** [mikel-brostrom/Yolov5_StrongSORT_OSNet#439]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,

I am using your project for a personal project and found out that I faced an issue as described in the title.

`pred = self.model(im, augment=self.augment, visualize=False)`

is the line that the problem starts with in track.py. 

I don't understand the inner workings of yolo v5 or maybe neural networks enough to debug this, why is there a need to concatenate two tensors, and which tensors are being concatenated? Why is a must it be size 46 and what is giving it size 45?

self.model is initialised as:
`self.model = DetectMultiBackend(self.yolo_weights, device=self.device, dnn=self.dnn, data=None, fp16=self.half)`
where self.yolo_weights is yolov5m.pt
 
im is an image of `torch.Size([1, 3, 720, 1280])`. self.augment is False.

The full error code is shown below:
```Traceback (most recent call last):
 File "/home/evas/Desktop/GEVAS_II_GCS/Yolov5_StrongSORT_OSNet/track.py", line 158, in run
    pred = self.model(im, augment=self.augment, visualize=False)
  File "/home/evas/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/evas/Desktop/GEVAS_II_GCS/Yolov5_StrongSORT_OSNet/yolov5/models/common.py", line 452, in forward
    y = self.model(im, augment=augment, visualize=visualize)[0]
  File "/home/evas/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/evas/Desktop/GEVAS_II_GCS/Yolov5_StrongSORT_OSNet/yolov5/models/yolo.py", line 135, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/evas/Desktop/GEVAS_II_GCS/Yolov5_StrongSORT_OSNet/yolov5/models/yolo.py", line 160, in _forward_once
    x = m(x)  # run
  File "/home/evas/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/evas/Desktop/GEVAS_II_GCS/Yolov5_StrongSORT_OSNet/yolov5/models/common.py", line 305, in forward
    forward = torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 46 but got size 45 for tensor number 1 in the list.
```

If there is any additional information do let me know, thank you so much for your help :D

**Comment by mikel-brostrom** [comment]
This is a Yolov5 question. Drop it in: https://github.com/ultralytics/yolov5/issues
