### ISSUE TITLE
Reading the .pt file shows Unknown model: None.

### ISSUE THREAD

**Issue by jklkid** [mikel-brostrom/Yolov5_StrongSORT_OSNet#483]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I converted the downloaded osnet_x0_25_msmt17_256x128_amsgrad_ep180_stp80_lr0.003_b128_fb10_softmax_labelsmooth_flip .pth file into a osnet_x0_25_msmt17 .pt file and put it in the corresponding location to run track.py. After that the following error occurred:
Traceback (most recent call last):
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\track.py", line 323, in <module>
    main(opt)
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\track.py", line 318, in main
    run(**vars(opt))
  File "D:\Anaconda3\envs\deepsort\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\track.py", line 119, in run
    StrongSORT(
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\strong_sort\strong_sort.py", line 34, in __init__
    self.model = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\strong_sort\reid_multibackend.py", line 48, in __init__
    self.extractor = FeatureExtractor(
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\strong_sort\torchreid\utils\feature_extractor.py", line 71, in __init__
    model = build_model(
  File "D:\project_Yolov5_StrongSORT_OSNet\Yolov5_StrongSORT_OSNet-master\strong_sort\torchreid\models\__init__.py", line 111, in build_model
    raise KeyError(
KeyError: "Unknown model: None. Must be one of ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d', 'resnext101_32x8d', 'resnet50_fc512', 'se_resnet50', 'se_resnet50_fc512', 'se_resnet101', 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'densenet121_fc512', 'inceptionresnetv2', 'inceptionv4', 'xception', 'resnet50_ibn_a', 'resnet50_ibn_b', 'nasnsetmobile', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4', 'shufflenet', 'squeezenet1_0', 'squeezenet1_0_fc512', 'squeezenet1_1', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'mudeep', 'resnet50mid', 'hacnn', 'pcb_p6', 'pcb_p4', 'mlfn', 'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25', 'osnet_ibn_x1_0', 'osnet_ain_x1_0']"

The conversion method used is:
import torch
state_dict=torch.load(r"osnet_x0_25_msmt17_256x128_amsgrad_ep180_stp80_lr0.003_b128_fb10_softmax_labelsmooth_flip.pth")
torch.save(state_dict, 'osnet_x0_25_msmt17.pt')

**Comment by mikel-brostrom** [comment]
Just rename the file from '.pth' to '.pt'. This is not needed:

```python
import torch
state_dict=torch.load(r"osnet_x0_25_msmt17_256x128_amsgrad_ep180_stp80_lr0.003_b128_fb10_softmax_labelsmooth_flip.pth")
torch.save(state_dict, 'osnet_x0_25_msmt17.pt')
```

The locate the path to you weights. For example: `/path/to/my/osnet_x0_25_msmt17.pt`
Then run track.py with that path for the strongsort weights.

```bash
python track.py --source 0 --strong-sort-weights /path/to/my/osnet_x0_25_msmt17.pt
```
