### ISSUE TITLE
Error running DeepSort in CoLab

### ISSUE THREAD

**Issue by duane-edgington** [mikel-brostrom/Yolov5_StrongSORT_OSNet#503]
I am running 
colab yolov5 deepsort tutorial (which is actually using StrongSort
https://colab.research.google.com/drive/18nIqkBr68TkK8dHdarxTco6svHUJGggY?usp=sharing

I am getting the error:
YOLOv5 🚀 2022-8-24 Python-3.7.13 torch-1.12.1+cu113 CUDA:0 (Tesla T4, 15110MiB)

Fusing layers... 
Model summary: 308 layers, 21041679 parameters, 0 gradients
Traceback (most recent call last):
  File "track.py", line 323, in <module>
    main(opt)
  File "track.py", line 318, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 129, in run
    ema_alpha=cfg.STRONGSORT.EMA_ALPHA,
  File "/content/Yolov5_StrongSORT_OSNet/strong_sort/strong_sort.py", line 34, in __init__
    self.model = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
  File "/content/Yolov5_StrongSORT_OSNet/strong_sort/reid_multibackend.py", line 38, in __init__
    model_name = get_model_name(weights)
  File "/content/Yolov5_StrongSORT_OSNet/strong_sort/deep/reid_model_factory.py", line 124, in get_model_name
    if x in model.stem:
AttributeError: 'str' object has no attribute 'stem'

Has this error been introduced by the recent modification to:
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/strong_sort/deep/reid_model_factory.py
??

**Comment by mikel-brostrom** [comment]
Tried it, it works with the latest pushes

**Comment by duane-edgington** [comment]
Thank you Mikel Brostrom. I confirm now fixed. I appreciate the quick response.
