### ISSUE TITLE
Running a tensorrt engine from reid_export causes an "Error Code 4: Internal Error (Engine deserialization failed.)"

### ISSUE THREAD

**Issue by HighMans** [mikel-brostrom/Yolov5_StrongSORT_OSNet#525]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Tracking, Other

### Bug

Hello,

When trying to use the engine exported from reid_export.py  for tracking, an error occurs below:

```
[09/14/2022-15:34:35] [TRT] [I] Loaded engine size: 8 MiB
[09/14/2022-15:34:35] [TRT] [E] 1: [pluginV2Runner.cpp::load::293] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[09/14/2022-15:34:35] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "track.py", line 328, in <module>
    main(opt)
  File "track.py", line 323, in main
    run(**vars(opt))
  File "/home/highmans/Downloads/YoloV5/yolov5venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 123, in run
    StrongSORT(
  File "/home/highmans/Downloads/Yolov5_StrongSORT_OSNet/strong_sort/strong_sort.py", line 35, in __init__
    self.model = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
  File "/home/highmans/Downloads/Yolov5_StrongSORT_OSNet/strong_sort/reid_multibackend.py", line 100, in __init__
    self.context = self.model_.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

However, running track.py with the pth files themselves is okay.

### Environment

- YOLO: yolov5 @ 91a81d4
- StrongSORT: osnet_ain_x1_0_imagenet.pth or osnet_x1_0_imagenet.pth
- OS: Ubuntu 20.04.5LTS
- Python: 3.8.10

### Minimal Reproducible Example

python reid_export.py --weights osnet_x1_0_imagenet.pth  --include onnx engine --device 0
ython track.py --source in.mp4 --yolo-weights yolov5x6.engine --img 1280 --classes 5 2 3 --strong-sort-weights osnet_x1_0_imagenet.pt --save-vid

**Comment by mikel-brostrom** [comment]
Have you tried to pull the latest?
