### ISSUE TITLE
[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机 没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by liziliang123** [mikel-brostrom/Yolov5_StrongSORT_OSNet#536]
### Search before asking

- [x] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

运行track.py

出现：

Fusing layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients

Traceback (most recent call last):
  File "C:\Users\Tom\PycharmProjects\Yolov5_StrongSORT_OSNet\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Tom\PycharmProjects\Yolov5_StrongSORT_OSNet\venv\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Tom\PycharmProjects\Yolov5_StrongSORT_OSNet\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:                                                                           

Traceback (most recent call last):
  File "C:\Users\Tom\PycharmProjects\Yolov5_StrongSORT_OSNet\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
  File "C:\Users\Tom\PycharmProjects\Yolov5_StrongSORT_OSNet\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Tom\PycharmProjects\Yolov5_StrongSORT_OSNet\venv\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e (Caused by NewCon
nectionError('<urllib3.connection.HTTPSConnection object at 0x00000127702D3580>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机
没有反应，连接尝试失败。'))

这个是因为需要翻墙吗？还是其他原因。

**Comment by liziliang123** [comment]
解决了
是因为 osnet_x0_25_msmt17.pt 没有放到正确位置，在strong_sort/deep/checkpoint下，直接复制过来即可

**Comment by 2bhuanleduo** [comment]
您好，我也遇到这个问题，请问您最后是将osnet_x0_25_msmt17.pt放置在哪个文件夹下呢？

**Comment by 2bhuanleduo** [comment]
> 解决了 是因为 osnet_x0_25_msmt17.pt 没有放到正确位置，在strong_sort/deep/checkpoint下，直接复制过来即可

您好，我也遇到这个问题，请问您最后是将osnet_x0_25_msmt17.pt放置在哪个文件夹下呢？

**Comment by liziliang123** [comment]
> > 解决了 是因为 osnet_x0_25_msmt17.pt 没有放到正确位置，在strong_sort/deep/checkpoint下，直接复制过来即可
> 
> 您好，我也遇到这个问题，请问您最后是将osnet_x0_25_msmt17.pt放置在哪个文件夹下呢？

ROOT / 'weights'

**Comment by Qchacha** [comment]
我没有这个文件 这个文件本来是在哪的 osnet_x0_25_msmt17.pt
