### ISSUE TITLE
 HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e

### ISSUE THREAD

**Issue by 2bhuanleduo** [mikel-brostrom/Yolov5_StrongSORT_OSNet#553]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi, I got a question here and couldn't solve by myself. 

I downloaded the code and crowdhuman_yolov5m.pt model to my local repositoryand ran it according to README.md, the command like this:
`python track.py --yolo-weights yolov5/crowdhuman_yolov5m.pt --strong-sort-weights osnet_x0_25_msmt17.pt --source test.mp4 --save-vid --classes 0`
But something worng here
`Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000023F6766BB80>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023F6766BB80>: Failed to establish a new
 connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "track.py", line 333, in <module>
    main(opt)
  File "track.py", line 328, in main
    run(**vars(opt))
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 126, in run
    StrongSORT(
  File "D:\Git_repository\Yolov5_StrongSORT_OSNet\strong_sort\strong_sort.py", line 35, in __init__
    self.model = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
  File "D:\Git_repository\Yolov5_StrongSORT_OSNet\strong_sort\reid_multibackend.py", line 57, in __init__
    gdown.download(model_url, str(w), quiet=False)
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\gdown\download.py", line 146, in download
    res = sess.get(url, headers=headers, stream=True, verify=verify)
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Software\Anaconda3\envs\strongsort\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023F6766BB80>: Failed to establish a
new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))`

Can anyone help me solve it? Thanks!

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/277

**Comment by 2bhuanleduo** [comment]
Thanks! Now it works.

**Comment by zzr2311559** [comment]
This repo has been updated recently and some pathes as well as some files changed as a result. 
I came up with the same problem and tried this method, then found that the reid weights file currently used are not suffixed with "imagenet" anymore, for instance https://drive.google.com/uc?id=1uwA9fElHOk3ZogwbeY5GkLI6QPTX70Hq gives "osnet_x0_75_imagenet.pth" which is not supported now.
I have found that \Yolov5_StrongSORT_OSNet\trackers\strong_sort\deep\checkpoint\ looks like the "checkpoints" directory [dacapo-rgb](https://github.com/dacapo-rgb) mentioned in https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/277 but I'm not sure. This directory already contained some weights files and I have tried to copy one of the file to the .cache/torch/checkpoints in my usr folder, since torch/checkpoints is not exist, I make the path manually, but it seems can not work.
Could you give me some advice?

**Comment by LeSoleil1** [comment]
> This repo has been updated recently and some pathes as well as some files changed as a result. I came up with the same problem and tried this method, then found that the reid weights file currently used are not suffixed with "imagenet" anymore, for instance https://drive.google.com/uc?id=1uwA9fElHOk3ZogwbeY5GkLI6QPTX70Hq gives "osnet_x0_75_imagenet.pth" which is not supported now. I have found that \Yolov5_StrongSORT_OSNet\trackers\strong_sort\deep\checkpoint\ looks like the "checkpoints" directory [dacapo-rgb](https://github.com/dacapo-rgb) mentioned in #277 but I'm not sure. This directory already contained some weights files and I have tried to copy one of the file to the .cache/torch/checkpoints in my usr folder, since torch/checkpoints is not exist, I make the path manually, but it seems not work. Could you give me some advice?

A solution would be something like this:
1- The 'weights' folder doesn't exist. So, create this folder in the 'root' of the project.
2-  You can find some weights, especially the default ones, in the 'trackers/strongsort/deep/checkpoint/' folder. You need to copy them to the 'weights' folder. Then rename these files and change their extension from '.pth' to '.pt'
**_Note:_** You can find the weights URLs in the 'trackers/strongsort/deep/reid_model_factory.py' file. You can manually download these weights using those URLs and put them in the 'weights' folder. Important to note that the files have different extensions like '.pth' and you should change their extension to '.pt'.

I hope it helps.
