### ISSUE TITLE
eval stronsort with yolo

### ISSUE THREAD

**Issue by irfanfadhullah** [mikel-brostrom/Yolov5_StrongSORT_OSNet#600]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

when i try to follow the instruction in the repo, i got an error, can you help me to solve this error?

```(reid) v2t@V2T-ICL:/media/v2t/Data/reid/github/new/Yolov5_StrongSORT_OSNet$ python val.py --benchmark MOT17 --tracking-method ocsort --yolo-weights weights/best.pt
val: yolo_weights=['weights/best.pt'], reid_weights=/media/v2t/Data/reid/github/new/Yolov5_StrongSORT_OSNet/weights/osnet_x1_0_dukemtmcreid.pt, tracking_method=ocsort, name=exp, project=runs/track, exist_ok=False, benchmark=MOT17, split=train, eval_existing=, conf_thres=0.45, imgsz=[1280], device=['']
default message here: Parse error at "'+https:/'": Expected stringEnd
Eval repo already downloaded
Traceback (most recent call last):
  File "val.py", line 189, in <module>
    main(opt)
  File "val.py", line 147, in main
    p = subprocess.Popen(["python", "track.py",\
  File "/home/v2t/anaconda3/envs/reid/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/v2t/anaconda3/envs/reid/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by mikel-brostrom** [comment]
Cannot reproduce as you are using anaconda, try to create a pip environment and provide a minimal reproducible example

**Comment by irfanfadhullah** [comment]
I have follow the step how ot evaluate in this link 
```https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/wiki/MOT-17-evaluation-(private-detector)
and
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/wiki/How-to-evaluate-on-custom-tracking-dataset
``` 

and this is the command that i used to do evaluate the MOT17
```python val.py --benchmark MOT17 --tracking-method ocsort --yolo-weights weights/best.pt```
and the error also appear on MOT20

**Comment by mikel-brostrom** [comment]
Based on this:

```bash
TypeError: expected str, bytes or os.PathLike object, not list
```

`yolo_weights` should be a string, not a list

**Comment by mikel-brostrom** [comment]
Fixed

**Comment by irfanfadhullah** [comment]
Problem solved, thank you for your help. I will close this issue.
