### ISSUE TITLE
track.run() error

### ISSUE THREAD

**Issue by OakGroove** [mikel-brostrom/Yolov5_StrongSORT_OSNet#689]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Tracking

### Bug

Sorry to bring it up again, but it seems that one of the updates has disabled the use of the track.run() function within a python script. The set up is as so:
![image](https://user-images.githubusercontent.com/93164738/211840419-ce6235ca-6166-4099-9e74-2277f1a68f4f.png)

This is the output I get when ran:
`Fusing layers...`
`YOLOv5x summary: 444 layers, 86765005 parameters, 0 gradients, 205.5 GFLOPS`
`Traceback (most recent call last):`
`File "c: /Users/user/Desktop/Notebooks/tracking-workflow/Yolov5_StrongSORT_OSNet/script_test.py", line 7, in <module> track.run(yolo_weights=pt, source=vid)`
`File "c: \Users\user\.conda\envs\ds-b-sys\lib\site-packages\torch\autograd\grad_mode.py", line26, in decorate_context return func(*args, **kwargs)`
`File "c:\Users\user\Desktop\notebook\tracking-workflow\Yolov5_StrongSORT_OSNet\track.py", line 118, in run tracker = create_tracker(tracking_method, tracking_config, reid_weights, device, half)`
`File "c: \Users\user\Desktop\notebooks\tracking-workflow\Yolov5_StrongSORT_OSNet\trackers\multi_tracker_zoo.py", line 10, in create_tracker cfg.merge_from_file(tracker_config)`
`File "c:\Users\user\Desktop\notebooks\tracking-workflow\Yolov5_StrongSORT_OSNet\trackers\strongsort\utils\parser.py", line 24, in merge_from_file with open(config_file, 'r') as fo:`
`TypeError: expected str, bytes or os.PathLike object, not NoneType`

From what I can see, it has to do with the path for the yolo weights file (removing the Path() function will return the `AttributeError: 'str' object has no attribute 'stem'` error). Giving the relative path nets the same result, so I don't think that's the issue. 
Is there something I'm missing out on?

**Comment by OakGroove** [comment]
Yep that worked. Thanks a bunch. I did get an error however about bot being able to find the ‘weights’ file in the main repository, though I was able to add it manually and it works fine now.
